# Este fluxo de trabalho (workflow) construirá um projeto Java com Maven e armazenará/restaurará quaisquer dependências para melhorar o tempo de execução do fluxo de trabalho.
# Para obter mais informações, consulte: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Este fluxo de trabalho usa ações que não são certificadas pelo GitHub.
# Elas são fornecidas por terceiros e são regidas por
# termos de serviço, política de privacidade e documentação de suporte separados.

name: Java CI com Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Construir com Maven
      run: mvn -B package --file pom.xml

    # Opcional: Faz o upload do gráfico de dependências completo para o GitHub para melhorar a qualidade dos alertas do Dependabot que este repositório pode receber
    - name: Atualizar gráfico de dependências
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
